// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTAWfKm5VdjcIHcq1_HH7piLnI25boPY',
    appId: '1:796962857071:web:4757469d7d5b5dd7c32d9a',
    messagingSenderId: '796962857071',
    projectId: 'bantuone-sunib',
    authDomain: 'bantuone-sunib.firebaseapp.com',
    databaseURL: 'https://bantuone-sunib-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bantuone-sunib.appspot.com',
    measurementId: 'G-K4X6C92JC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnr6ZAu7DgRpHZ4QcJvmqy7lu7jgAFyU',
    appId: '1:796962857071:android:0dee180b5fa16a63c32d9a',
    messagingSenderId: '796962857071',
    projectId: 'bantuone-sunib',
    databaseURL: 'https://bantuone-sunib-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bantuone-sunib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1jobW2bdxSGgev40vE8-cJ1ZTmaDkVs',
    appId: '1:796962857071:ios:2774ff4d9f5aa657c32d9a',
    messagingSenderId: '796962857071',
    projectId: 'bantuone-sunib',
    databaseURL: 'https://bantuone-sunib-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bantuone-sunib.appspot.com',
    androidClientId: '796962857071-36k5bkefvka5c903k7pvpik2c300nphm.apps.googleusercontent.com',
    iosClientId: '796962857071-c98kpp0v0onfjkr0pj8e9jtonubc7l4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bantuoneAdmin',
  );
}
